engines:
  eslint:
    enabled: true

  duplication:
    enabled: false
    config:
      languages:
        - javascript

ratings:
  paths:
    - controllers/**
    - dao/**
    - models/**
    - modules/**
    - routers/**

exclude_paths:
  - bin/**
  - node_modules/**/*
  - test/**
